spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

app:
  redis:
    enabled: true
  storage:
    type: ${APP_STORAGE_TYPE:local}
    bucket: ${APP_STORAGE_BUCKET:}

logging:
  level:
    root: INFO
